# Gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: waitroom-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - waitroom-gateway
  http:
  - match:
    - uri:
        prefix: /auth/
    route:
    - destination:
        host: proxy-service
        port:
          number: 80
  - match:
    - headers:
        waitroom-test:
          exact: travis
    route:
    - destination:
        host: proxy-service
        port:
          number: 80
---
# Each instance of proxy-service is stateless so we need to be sure traffic is forwarded to the same pod
# See: https://istio.io/latest/docs/reference/config/networking/destination-rule/#LocalityLoadBalancerSetting
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: proxy-service
spec:
    host: proxy-service.default.svc.cluster.local
    trafficPolicy:
      loadBalancer:
        consistentHash:
          useSourceIp: true